import { useState } from 'react'
import { Link, NavLink, useLocation } from 'react-router-dom'
import { Menu, ShoppingBag, UtensilsCrossed, X } from 'lucide-react'
import { cartItemCount, useCartStore } from '../../store/cartStore'
import { withTable } from '../../lib/table'

export function Layout({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false); const location = useLocation(); const table = new URLSearchParams(location.search).get('table'); const count = useCartStore((state) => cartItemCount(state.items)); const to = (path: string) => withTable(path, table)
  const navClass = ({ isActive }: { isActive: boolean }) => `transition hover:text-terracotta ${isActive ? 'text-terracotta font-semibold' : ''}`
  return <div className="min-h-screen"><header className="sticky top-0 z-30 border-b border-stone-200 bg-cream/95 backdrop-blur"><nav className="mx-auto flex h-18 max-w-6xl items-center justify-between px-4 sm:px-6"><Link to={to('/')} className="flex items-center gap-2 text-xl font-bold"><span className="grid size-9 place-items-center rounded-xl bg-terracotta text-white"><UtensilsCrossed size={19} /></span>SajiTap</Link><div className="hidden items-center gap-7 text-sm md:flex"><NavLink className={navClass} to={to('/')}>Beranda</NavLink><NavLink className={navClass} to={to('/menu')}>Menu</NavLink></div><div className="flex items-center gap-2"><Link aria-label="Keranjang" to={to('/cart')} className="relative grid size-10 place-items-center rounded-full hover:bg-orange-100"><ShoppingBag size={20}/>{count > 0 && <span className="absolute -right-1 -top-1 grid size-5 place-items-center rounded-full bg-terracotta text-[11px] font-bold text-white">{count}</span>}</Link><button className="grid size-10 place-items-center rounded-full hover:bg-orange-100 md:hidden" aria-label={open ? 'Tutup navigasi' : 'Buka navigasi'} onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button></div></nav>{open && <div className="border-t border-stone-200 bg-cream px-6 py-4 md:hidden"><div className="mx-auto flex max-w-6xl flex-col gap-3"><NavLink onClick={() => setOpen(false)} className={navClass} to={to('/')}>Beranda</NavLink><NavLink onClick={() => setOpen(false)} className={navClass} to={to('/menu')}>Menu</NavLink></div></div>}</header><main>{children}</main><footer className="mt-16 border-t border-stone-200 bg-white"><div className="mx-auto flex max-w-6xl flex-col gap-3 px-4 py-8 text-sm text-stone-500 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div><strong className="text-ink">SajiTap</strong><span className="ml-2">Tap. Order. Enjoy.</span></div><p>Restaurant table-ordering experience · Portfolio project</p></div></footer></div>
}
