import { CheckCircle2, ChevronLeft, ShoppingBag } from 'lucide-react'
import { useState } from 'react'
import { Link, useLocation, useParams } from 'react-router-dom'
import { QuantityStepper } from '../components/ui/QuantityStepper'
import { getMenuItem } from '../data/menu'
import { formatRupiah } from '../lib/format'
import { withTable } from '../lib/table'
import { useCartStore } from '../store/cartStore'
export function MenuDetailPage() { const { id } = useParams(); const item = getMenuItem(id ?? ''); const [quantity, setQuantity] = useState(1); const [note, setNote] = useState(''); const [added, setAdded] = useState(false); const addItem = useCartStore((state) => state.addItem); const location = useLocation(); const table = new URLSearchParams(location.search).get('table'); if (!item) return <section className="mx-auto max-w-xl px-4 py-24 text-center"><h1 className="font-display text-4xl">Menu tidak ditemukan</h1><p className="mt-3 text-stone-600">Menu ini mungkin sudah tidak tersedia.</p><Link className="mt-6 inline-block font-semibold text-terracotta" to={withTable('/menu', table)}>Kembali ke menu</Link></section>; const add = () => { addItem(item, quantity, note); setAdded(true); window.setTimeout(() => setAdded(false), 2500) }; return <section className="mx-auto max-w-5xl px-4 py-8 sm:px-6"><Link to={withTable('/menu', table)} className="inline-flex items-center gap-1 text-sm font-semibold text-stone-600 hover:text-terracotta"><ChevronLeft size={17}/> Kembali ke menu</Link><div className="mt-6 grid gap-8 lg:grid-cols-2"><img src={item.image} alt={item.name} className="aspect-square w-full rounded-3xl object-cover shadow-lg"/><div className="lg:py-4"><p className="text-sm font-bold uppercase tracking-widest text-terracotta">{item.category}</p><h1 className="mt-2 font-display text-4xl">{item.name}</h1><p className="mt-4 leading-relaxed text-stone-600">{item.description}</p><p className="mt-6 text-2xl font-bold">{formatRupiah(item.price)}</p>{item.available ? <div className="mt-8 space-y-6"><div><p className="mb-2 text-sm font-semibold">Jumlah pesanan</p><QuantityStepper value={quantity} onChange={setQuantity}/></div><label className="block text-sm font-semibold">Catatan pesanan<textarea value={note} onChange={(event) => setNote(event.target.value)} className="mt-2 min-h-25 w-full rounded-xl border border-stone-300 bg-white p-3 font-normal outline-none focus:border-terracotta" placeholder="Contoh: Tidak pedas, sambal dipisah"/></label><div className="flex items-center justify-between rounded-xl bg-orange-50 p-4"><span className="font-semibold">Subtotal</span><span className="text-xl font-bold text-terracotta">{formatRupiah(item.price * quantity)}</span></div><button onClick={add} className="flex w-full items-center justify-center gap-2 rounded-xl bg-terracotta px-5 py-3.5 font-bold text-white hover:bg-[#7f2e18]"><ShoppingBag size={19}/> Tambah ke Keranjang</button>{added && <p role="status" className="flex items-center justify-center gap-2 font-semibold text-emerald-700"><CheckCircle2 size={18}/> Berhasil ditambahkan ke keranjang</p>}</div> : <div className="mt-8 rounded-xl bg-stone-100 p-5"><p className="font-semibold">Menu sedang habis</p><p className="mt-1 text-sm text-stone-600">Silakan pilih hidangan lain yang tersedia.</p></div>}</div></div></section> }
